### ISSUE TITLE
Elastic box results filename has changed

### ISSUE THREAD

**Issue by stdnmr** [smash-transport/smash-analysis#11]
... therefore the old results extraction script has to be slightly changed. Old filename was just `scatrate_vs_SETUP.txt`. New filename is `scatrate_vs_SETUP-geometric.txt` (or `stochastic`).

Refs #1

**Comment by akschaefer** [comment]
Turns out this is not a problem after all, as the files are found according to 
```bash
find elastic_box -maxdepth 2 -name "scatrate_vs_*.txt" | xargs cp -t ${store_dir}/elastic_box/
```

I verified that everything works as expected. Therefore closing the issue.
