### ISSUE TITLE
Update reader script for format version 7

### ISSUE THREAD

**Issue by doliinychenko** [smash-transport/smash-analysis#12]
Getting this error reading newest SMASH output:
`Fatal error: unknown format version =  7`

**Comment by vks** [comment]
I have a local version that supports the new format. I will open a PR tomorrow.

**Comment by doliinychenko** [comment]
Thanks! What's a PR? Also, could you please give me a right to set assignees, labels, etc?

**Comment by vks** [comment]
> Ok, PR must be Pull Request.

Yes, you got it, sorry for the GitHub slang.

> Also, could you please give me a right to set assignees, labels, etc?

I cannot set anything either. I'll bring it up in the group (probably next week, because now almost nobody is here).
