### ISSUE TITLE
Python packages error messages

### ISSUE THREAD

**Issue by Woolitzer** [smash-transport/smash-analysis#18]
I ran into minor things running the analysis suite on the goethe cluster for the first time:

The required module named _yaml_ is the python module _pyyaml_, I think. 

Further, one could add the required version to the error message when the module is not found at all. It's helpful to know which one to install.

I could quickly take care of that if you agree @akschaefer.

**Comment by akschaefer** [comment]
Feel free to take care of it, @Woolitzer :)
