### ISSUE TITLE
Clean up detailed balance plots

### ISSUE THREAD

**Issue by akschaefer** [smash-transport/smash-analysis#2]
The center panel of the detailed balance plots looks a bit messy and wobbles around a lot. They should be cleaned up by - for example - reducing the number of bins to make it smoother.

**Comment by akschaefer** [comment]
@NGoetz will check whether this still needs attention and take care of it, if necessary.

**Comment by NGoetz** [comment]
As we have currently one panel on the left and three on the right, I am not really sure which of the plots is meant - the central one on the right?

**Comment by akschaefer** [comment]
After discussing again with @NGoetz we have decided that this is not really an issue anymore, so we close it.
