### ISSUE TITLE
Finding non default smash executable when using containers

### ISSUE THREAD

**Issue by gabriele-inghirami** [smash-transport/smash-analysis#36]
In principle the following issue should apply to all cases in which the user has a permanent SMASH installation with dedicated system wide environment variables, but it is much more likely that it is found when using Singularity containers, e.g. in the Virgo Cluster.

When running the analyses, the SMASH executable is found by the cmake _find_program_  command, which first searches in the default system directories and then in the additional directories in SMASH_PATH. 
See: https://cmake.org/cmake/help/latest/command/find_program.html
So, when using a container, the pre-compiled SMASH version shipped with the container will be find first and used.
This is a problem when somebody wants to test a different SMASH branch, not the default stable one.

The first solution, which has been tested by Anna and me, is:

- add the flag `NO_DEFAULT_PATH` in _CMakeLists_.txt when calling  _find_program_ : ` find_program(SMASH smash PATHS ${SMASH_PATH} NO_DEFAULT_PATH)` and then, in the script run by SLURM, set and export the SMASH_PATH variable:
```
export SMASH_PATH=$smash_dir
cmake -DSMASH_PATH=$build_dir -DEXP_DATA=$EXP_DATA_DIR -B$output_dir -H$analysis_dir 
```

Another solution, that worked for me, but maybe not for Anna, is to prepend the path of the chosen non default SMASH installation to the PATH variable in the script run by SLURM, e.g.:
```
export PATH=$smash_dir:$PATH
cmake -DSMASH_PATH=$build_dir -DEXP_DATA=$EXP_DATA_DIR -B$output_dir -H$analysis_dir
```
without modifying CMakeLists.txt.

Exporting the updated PATH variable before starting the container does not work, because, as written in the Singularity documentation https://sylabs.io/guides/3.6/user-guide/environment_and_metadata.html, all environment variables are transmitted to the container, except PATH , PS1 (for the shell prompt) and LD_LIBRARY_PATH (for the location of the shared libraries), which are reset by the container. So, PATH must be set when already running the container. However, if needed, it is possible to override the default values by calling singularity with the --env option, but this solution looks more complicated than the others.

This issue applies also to the smash-analyis-extra repository, but I don't see the need to open a duplicated issue there. Once we have decided how to deal with this stuff, we can apply the same solution to the other repo.
@akschaefer @elfnerhannah @stdnmr

**Comment by stdnmr** [comment]
```
export SMASH_PATH=$smash_dir
cmake -DSMASH_PATH=$build_dir -DEXP_DATA=$EXP_DATA_DIR -B$output_dir -H$analysis_dir 
```
You do either of those not both, right? Or why does one need `-DSMASH_PATH=$build_dir`, when SMASH_PATH was already exported?

**Comment by stdnmr** [comment]
I think you first solution sounds good to me. I think NO_DEFAULT_PATH could be set by default, since we usually are not relying on finding the smash executable in default paths.

**Comment by gabriele-inghirami** [comment]
I opened a trivial PR. Better to move the discussion there, closing this issue.
