### ISSUE TITLE
Fix p + p->p + p + eta cross section

### ISSUE THREAD

**Issue by akschaefer** [smash-transport/smash-analysis#4]
The plot for the reconstruction of the p+p+eta cross section is broken. See for example [here](http://theory.gsi.de/~smash/analysis_suite/SMASH-1.6/cross_sections/).

It cannot simply be solved by removing the eta from the list of unstable particles. In this case some assertion that the cross section is greater than 0 fails.

@stdnmr @vks

**Comment by stdnmr** [comment]
Ok, I confirmed that there is still a reasonable number of etas produced. See the results table below. Cross section results are estimates with the total pp cross section as 40 mb.

sqrt(s) | 3.0 GeV | 4.0 GeV
-------|---- |-----
Avg. N_eta | 0.0119 | 0.032
XS(pp->eta+X) | 0.4 mb | 1.28mb

**Comment by RenHirayama** [comment]
This was fixed by #72.
