### ISSUE TITLE
Port analysis suite to python 3

### ISSUE THREAD

**Issue by vks** [smash-transport/smash-analysis#5]
Support for Python 2 is running out by the end of this year, so we should migrate to Python 3. @janusw worked on this before (see https://pm.fias.science/issues/1147), but there were serious performance regressions.

**Comment by vks** [comment]
More information: https://www.python.org/doc/sunset-python-2/

**Comment by vks** [comment]
This was not fixed!

**Comment by akschaefer** [comment]
Must have been a wrong reference.

**Comment by elfnerhannah** [comment]
This should be done soon, since support is really running out for 2.X.

**Comment by stdnmr** [comment]
I have started to fix some issues that pop up when trying to import the basic scripts with python3 on `staudenamier/porting-basic-scripts-to-python3`

**Comment by elfnerhannah** [comment]
@gabriele-inghirami also started to work on this, so please make sure to not duplicate work.

**Comment by stdnmr** [comment]
Yep, I just quickly fixed a couple of issues for myself and thought I leave them here.

**Comment by doliinychenko** [comment]
@gabriele-inghirami @stdnmr Looking forward to your results on this issue. I was working on JetScape summer school SMASH hands-on and their docker environment has only python3. So I had to dirty-translate some scripts into python3. I will be happy to review.

**Comment by elfnerhannah** [comment]
I guess, this is another pointer that this issue should not be forgotten. Still the last deadline is our next public release this Fall.

**Comment by gabriele-inghirami** [comment]
We might still find here and there something to fix, but I would say that the porting is complete.
