### ISSUE TITLE
Unclear how to use generate_html.py

### ISSUE THREAD

**Issue by vks** [smash-transport/smash-analysis#7]
When running `generate_html.py` on a folder with plots, I get the following error:

```
Traceback (most recent call last):
  File "/home/steinberg/src/smash-analysis-new/test/report/generate_html.py", line 660, in <module>
    tree = reorder_tree(tree, source_dir.split('/')[-2])
IndexError: list index out of range
```

Apparently, the code makes some assumptions about the folder structure. However, they seem to be undocumented, so I don't know how invoke the script correctly.

Ideally, I think the code should be more robust and not make those assumptions.

**Comment by elfnerhannah** [comment]
Can we just add in the README where this script needs to be invoked?

**Comment by vks** [comment]
I think the right place for documentation would be [here](https://github.com/smash-transport/smash-analysis/blob/9ea4e6208f7b063de3537035759330301e87d6af/test/report/generate_html.py#L23) or [here](https://github.com/smash-transport/smash-analysis/blob/9ea4e6208f7b063de3537035759330301e87d6af/test/report/generate_html.py#L620). That way, the usage is explained when running `generate_html.py --help`.

**Comment by akschaefer** [comment]
@NGoetz will check whether this still needs attention and take care of it, if necessary.
