### ISSUE TITLE
Add list of possible targets

### ISSUE THREAD

**Issue by RenHirayama** [smash-transport/smash-analysis#73]
Would be good for users to have a list of possible targets, possibly via `make help`.

**Comment by AxelKrypton** [comment]
I totally agree, but I also know that CMake _should_ create a `help` target. 🤔 After some quick googling, I found
* [this answer](https://stackoverflow.com/a/41490195/14967071) where comments might hint that this is not universal on all OS and
* [this question](https://stackoverflow.com/q/30793804/14967071) which also says useful information.

Did you try to run `make help`? I assume we set up the project using CMake.
